version: '2'
services:
  todo-app:
    image: todo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://todo-mysql:3306/todo?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://todo-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://todo-elasticsearch:9200
    ports:
      - 8080:8080
  todo-mysql:
    extends:
      file: mysql.yml
      service: todo-mysql
  todo-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: todo-elasticsearch
